name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install compiler
      run: sudo snap install --classic kotlin
    - name: Run a multi-line script
      run: |
        kotlinc src/main.kt -include-runtime -d main.jar
